"""Gates for the doc facts that keep going stale.

Three classes of documentation defect have recurred often enough to be worth
a test rather than a review habit:

1. **Hand-copied measurements.** The advanced-mode schema footprint was
   written into six files and every one of them was stale — the v3.2.1 trim
   moved the number and nothing pointed at the docs. The measurement already
   exists in ``tests/test_phase_f_schema_budget.py``; this module reuses it
   and checks the prose against it.

2. **Version declarations that nobody stamps.** ``website/public/humans.txt``
   advertised ``Version: 2.1.7`` through eleven releases because it carried no
   ``x-release-please-version`` annotation and was not in ``extra-files``.
   ``test_mcpb_distribution`` pins the files that *are* annotated; this module
   sweeps the whole doc corpus for a declaration that should have been.

3. **A hand-transcribed API reference.** The published signature block for
   ``zim_get_section`` was missing ``include_subsections`` — a real parameter,
   documented nowhere on the site. The page tells readers "if signatures here
   disagree with code, file an issue", which is drift detection delegated to
   strangers. Parameter names, enum values and required-ness are checked here
   instead; the prose stays hand-written.
"""

from __future__ import annotations

import json
import re
import tempfile
from pathlib import Path

import pytest

from openzim_mcp import __version__
from openzim_mcp.config import OpenZimMcpConfig
from openzim_mcp.server import OpenZimMcpServer

REPO = Path(__file__).resolve().parents[1]

# Every documentation surface a reader can reach, plus the repo-root policy
# files. ``website/dist`` is build output and ``docs/superpowers`` is
# gitignored planning scratch, so neither is scanned.
_DOC_ROOTS = (
    [REPO / name for name in ("README.md", "CONTRIBUTING.md", "SECURITY.md")]
    + sorted((REPO / "docs").glob("*.md"))
    + sorted((REPO / "website" / "src").rglob("*.mdx"))
    + sorted((REPO / "website" / "src").rglob("*.astro"))
    + sorted((REPO / "website" / "public").glob("*.txt"))
    # llms.txt is generated by an endpoint now, so the text a reader
    # fetches lives in a .ts file. Without this line the corpus quietly
    # stopped covering it the moment the static file was deleted.
    # rglob, not glob: the per-page Markdown route lives one directory down,
    # and a non-recursive pattern would have skipped it.
    + sorted((REPO / "website" / "src" / "pages").rglob("*.ts"))
)


def _doc_files() -> list[Path]:
    return [p for p in _DOC_ROOTS if p.is_file()]


def test_doc_corpus_is_non_empty() -> None:
    """Guard the guards: a bad glob would make every scan below vacuous."""
    files = _doc_files()
    assert len(files) >= 20, f"doc corpus collapsed to {len(files)} files: {files}"


# --------------------------------------------------------------------------
# 1. The advertised schema footprint must match the measured one.
# --------------------------------------------------------------------------


# Mirrors ``_measure_tools`` in tests/test_phase_f_schema_budget.py — the wire
# bytes of everything ``tools/list`` actually ships. Duplicated rather than
# imported so a change to the budget test's helper cannot silently redefine
# what the docs are being checked against.
def _advanced_surface_bytes() -> int:
    allowed = tempfile.mkdtemp(prefix="openzim_mcp_docs_freshness_")
    cfg = OpenZimMcpConfig(allowed_directories=[allowed], tool_mode="advanced")
    srv = OpenZimMcpServer(cfg)
    total = 0
    for name, tool in srv.mcp._tool_manager._tools.items():
        payload = {
            "name": name,
            "description": tool.description,
            "inputSchema": tool.parameters,
        }
        if tool.output_schema is not None:
            payload["outputSchema"] = tool.output_schema
        total += len(json.dumps(payload, separators=(",", ":")).encode())
    return total


# "23,898 bytes" / "23,898-byte" — an exact byte count stated as fact.
# The negative lookbehind keeps this off the tail of a larger grouped number:
# without it, "10,000,000 bytes" (the binary cap) matches as "00,000 bytes".
_BYTES_RE = re.compile(r"(?<![\d,])(\d{2},\d{3})(?:[- ]byte\b|\s+bytes\b)")
# "~23.3KB" / "~23.3 KB" — the rounded figure, only when it is describing the
# advanced surface. Matched near the MCP-Tax/footprint prose to avoid catching
# unrelated sizes (the reranker's install footprint, ZIM file sizes).
_KB_RE = re.compile(r"~(\d{2}\.\d)\s?KB")

# Figures that are legitimately not the current measurement: the pre-
# consolidation v1 footprint quoted as a before/after, and the budget cap
# (which is a constant, not a measurement).
#
# The superseded measurement (25,432) is deliberately NOT exempt — that is
# exactly the value this gate exists to catch, and exempting it was how the
# first version of this test passed its own mutation check.
_FOOTPRINT_EXEMPT = ("~36KB", "25,600")


def test_advertised_schema_footprint_matches_measurement() -> None:
    measured = _advanced_surface_bytes()
    exact = f"{measured:,}"
    rounded = f"{measured / 1024:.1f}"

    bad: list[str] = []
    for path in _doc_files():
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            rel = path.relative_to(REPO)
            for m in _BYTES_RE.finditer(line):
                found = m.group(1)
                if found in _FOOTPRINT_EXEMPT or found == exact:
                    continue
                bad.append(f"{rel}:{lineno}: states {found} bytes")
            if "MCP Tax" in line or "wire footprint" in line or "schema" in line:
                for m in _KB_RE.finditer(line):
                    if m.group(1) == rounded:
                        continue
                    if f"~{m.group(1)}KB" in _FOOTPRINT_EXEMPT:
                        continue
                    bad.append(f"{rel}:{lineno}: states ~{m.group(1)}KB")

    assert not bad, (
        "the advanced-mode schema footprint is documented as a number that no "
        f"longer matches the surface. Measured now: {exact} bytes "
        f"(~{rounded}KB). Offending lines:\n  " + "\n  ".join(bad)
    )


# --------------------------------------------------------------------------
# 2. A version declaration must be stamped or current.
# --------------------------------------------------------------------------

# ``Version: 3.2.3``, ``"version": "3.2.3"``, ``**Version:** 3.2.3`` — a line
# declaring *this project's* version, as opposed to prose mentioning some past
# release ("shipped in v2.3.0"). Only declarations are checked: enumerating
# every historical mention in the corpus costs more than it catches, and a
# past-tense mention does not rot the way a bare declaration does.
_VERSION_DECL_RE = re.compile(r"""(?ix)
    (?:^|[\s*"'`|])              # start, or a markdown/JSON delimiter
    version                      # the literal word
    \**\s*[:=]\s*                # : or = (tolerating bold markers)
    \**["'v]*                    # optional quotes / a leading v
    (\d+\.\d+\.\d+)              # the semver
    """)

# Declarations that are deliberately not this project's version.
_FOREIGN_VERSION_CONTEXT = (
    "python",
    "libzim",
    "protocol",
    "schema",
    "sotoki",
    "node",
    "astro",
    "fastembed",
    "sidecar",
)


def test_version_declarations_are_stamped_or_current() -> None:
    """A bare ``Version: X.Y.Z`` in a doc rots at the next release."""
    offenders: list[str] = []
    for path in _doc_files():
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            if "x-release-please" in line:
                continue  # release-please stamps this line
            lowered = line.lower()
            if any(ctx in lowered for ctx in _FOREIGN_VERSION_CONTEXT):
                continue
            for found in _VERSION_DECL_RE.findall(line):
                if found == __version__:
                    continue
                rel = path.relative_to(REPO)
                offenders.append(f"{rel}:{lineno}: declares version {found}")

    assert not offenders, (
        f"version declarations that are neither stamped nor current "
        f"({__version__}):\n  " + "\n  ".join(offenders) + "\n"
        "Either add an `x-release-please-version` annotation to the line AND "
        "register the file in release-please-config.json's extra-files, or "
        "reword it so it is not a bare version declaration."
    )


# --------------------------------------------------------------------------
# 3. The API reference's signature blocks must match the live schemas.
# --------------------------------------------------------------------------

_API_REFERENCE = REPO / "website/src/content/docs/api-reference.mdx"

# ```python\nzim_get(\n    entry_path: str,\n ...\n) -> Any\n```
# Two shapes appear on the page: a multi-line block (one parameter per line)
# and a one-liner for the single-argument tools, e.g.
# ``zim_metadata(zim_file_path: str) -> Any``. Both must be recognised or a
# tool silently drops out of the parity check.
_SIGNATURE_RE = re.compile(r"```python\n(zim_[a-z_]+)\((.*?)\)\s*->", re.DOTALL)
# "    entry_path: Optional[str] = None," -> entry_path, in either shape.
_PARAM_RE = re.compile(r"(?:^\s*|,\s*|\(\s*)([a-z_][a-z0-9_]*)\s*:", re.MULTILINE)


def _documented_signatures() -> dict[str, set[str]]:
    text = _API_REFERENCE.read_text(encoding="utf-8")
    return {
        m.group(1): set(_PARAM_RE.findall(m.group(2)))
        for m in _SIGNATURE_RE.finditer(text)
    }


def _live_signatures() -> dict[str, set[str]]:
    allowed = tempfile.mkdtemp(prefix="openzim_mcp_docs_sig_")
    cfg = OpenZimMcpConfig(allowed_directories=[allowed], tool_mode="advanced")
    srv = OpenZimMcpServer(cfg)
    return {
        name: set((tool.parameters or {}).get("properties", {}))
        for name, tool in srv.mcp._tool_manager._tools.items()
    }


def test_api_reference_documents_every_advanced_tool() -> None:
    documented = _documented_signatures()
    live = _live_signatures()
    assert documented, "no ```python signature blocks parsed out of the page"
    missing = set(live) - set(documented)
    assert (
        not missing
    ), f"api-reference.mdx has no signature block for: {sorted(missing)}"
    unknown = set(documented) - set(live)
    assert not unknown, (
        f"api-reference.mdx documents tools that are not registered: "
        f"{sorted(unknown)}"
    )


@pytest.mark.parametrize("tool_name", sorted(_live_signatures()))
def test_api_reference_signature_parameters_match(tool_name: str) -> None:
    documented = _documented_signatures().get(tool_name)
    assert documented is not None, f"no signature block for {tool_name}"
    live = _live_signatures()[tool_name]

    undocumented = live - documented
    assert not undocumented, (
        f"{tool_name} accepts {sorted(undocumented)} but the published "
        "signature block omits them — a reader cannot discover the parameter. "
        "Add it to the signature block and the parameter table in "
        "website/src/content/docs/api-reference.mdx."
    )
    invented = documented - live
    assert not invented, (
        f"{tool_name}'s published signature block lists {sorted(invented)}, "
        "which the tool does not accept — calling it that way returns an "
        "`unknown_argument` envelope."
    )


def test_api_reference_enum_values_match() -> None:
    """Every enum the page spells out must be the enum the schema ships."""
    text = _API_REFERENCE.read_text(encoding="utf-8")
    live = _live_signatures()
    allowed = tempfile.mkdtemp(prefix="openzim_mcp_docs_enum_")
    cfg = OpenZimMcpConfig(allowed_directories=[allowed], tool_mode="advanced")
    srv = OpenZimMcpServer(cfg)

    missing: list[str] = []
    for name, tool in srv.mcp._tool_manager._tools.items():
        props = (tool.parameters or {}).get("properties", {})
        for param, spec in props.items():
            values = spec.get("enum")
            if not values:
                continue
            for value in values:
                if f'"{value}"' not in text and f"`{value}`" not in text:
                    missing.append(f"{name}.{param} value {value!r}")

    assert not missing, (
        "enum values accepted by the schema but never named on the API "
        f"reference page: {missing}. A value a reader cannot find is a value "
        "they cannot use."
    )
    assert live, "no live tools resolved"


# --------------------------------------------------------------------------
# 4. The sidebar's group list must cover the schema's group enum.
# --------------------------------------------------------------------------

_CONTENT_CONFIG = REPO / "website/src/content.config.ts"
_DOCS_ORDER = REPO / "website/src/lib/docs-order.ts"


def _ts_string_list(source: str, marker: str) -> list[str]:
    """Pull the quoted strings out of the array literal following ``marker``."""
    start = source.index(marker)
    body = source[start : source.index("]", start)]
    return re.findall(r"['\"]([^'\"]+)['\"]", body)


def test_sidebar_group_order_covers_the_schema_enum() -> None:
    """A group in the schema but not in GROUP_ORDER vanishes from the sidebar.

    ``Sidebar.astro`` renders one section per entry in ``GROUP_ORDER``. A page
    whose ``group`` is absent from that list passes frontmatter validation,
    builds without a warning, and is then silently unreachable from the nav —
    and ``sortDocsForNav`` pushes it to the end of the prev/next chain.
    """
    schema_groups = _ts_string_list(
        _CONTENT_CONFIG.read_text(encoding="utf-8"), "group: z.enum("
    )
    nav_groups = _ts_string_list(
        _DOCS_ORDER.read_text(encoding="utf-8"), "GROUP_ORDER = ["
    )
    assert schema_groups, "could not parse the group enum from content.config.ts"
    assert nav_groups, "could not parse GROUP_ORDER from docs-order.ts"
    assert set(schema_groups) == set(nav_groups), (
        "content.config.ts and docs-order.ts disagree about the doc groups.\n"
        f"  only in the schema:     {sorted(set(schema_groups) - set(nav_groups))}\n"
        f"  only in GROUP_ORDER:    {sorted(set(nav_groups) - set(schema_groups))}\n"
        "A group missing from GROUP_ORDER is dropped from the sidebar entirely."
    )


def test_every_doc_group_is_renderable() -> None:
    """Frontmatter must only use groups the sidebar knows how to render."""
    nav_groups = set(
        _ts_string_list(_DOCS_ORDER.read_text(encoding="utf-8"), "GROUP_ORDER = [")
    )
    bad: list[str] = []
    for page in sorted((REPO / "website/src/content/docs").glob("*.mdx")):
        match = re.search(r"^group:\s*(.+)$", page.read_text(encoding="utf-8"), re.M)
        if match is None:
            bad.append(f"{page.name}: no group in frontmatter")
        elif match.group(1).strip().strip("\"'") not in nav_groups:
            bad.append(f"{page.name}: group {match.group(1).strip()!r}")
    assert not bad, f"pages with a group the sidebar cannot render: {bad}"


# --------------------------------------------------------------------------
# 5. The social-preview image.
# --------------------------------------------------------------------------

_OG_SVG = REPO / "website/public/assets/og-image.svg"
_OG_PNG = REPO / "website/public/assets/og-image.png"


def test_social_preview_image_is_a_raster() -> None:
    """Scrapers do not render SVG, so the og:image must be the PNG.

    Facebook, X, LinkedIn, Slack and Discord all decline SVG og:images —
    pointing at one means every shared link previews with no image at all.
    """
    assert _OG_PNG.is_file(), "website/public/assets/og-image.png is missing"
    header = _OG_PNG.read_bytes()[:8]
    assert header == b"\x89PNG\r\n\x1a\n", "og-image.png is not a PNG"

    referenced: list[str] = []
    for rel in (
        "website/src/layouts/DocsLayout.astro",
        "website/src/pages/index.astro",
    ):
        text = (REPO / rel).read_text(encoding="utf-8")
        for match in re.finditer(
            r'(og:image|twitter:image)"\s+content="([^"]+)"', text
        ):
            if not match.group(2).endswith(".png"):
                referenced.append(f"{rel}: {match.group(1)} -> {match.group(2)}")
    assert not referenced, f"social images that are not the raster: {referenced}"


def test_social_preview_image_states_no_version() -> None:
    """The OG image shipped ``v1.1.1`` into the 3.x era.

    Nothing stamps an SVG text node, so a version baked into the artwork
    silently advertises a release that is majors behind on every shared link.
    Keep the artwork version-free.
    """
    # Only the rendered <text> content — path data is full of number triples
    # like "a3 3 0 1 0-5.997.125" that read as a semver to a naive scan.
    svg = _OG_SVG.read_text(encoding="utf-8")
    rendered = " ".join(re.findall(r"<text[^>]*>(.*?)</text>", svg, re.S))
    found = re.findall(r"v?\d+\.\d+\.\d+", rendered)
    assert not found, (
        f"og-image.svg names a version ({found}). Nothing updates it at "
        "release time, so it will be stale within one release — leave the "
        "version out of the artwork."
    )


# --------------------------------------------------------------------------
# 6. Documented rate-limit costs must match RATE_LIMIT_COSTS.
# --------------------------------------------------------------------------

# Four pages describe the rate limiter, each for a different audience: the API
# reference maps tool call -> internal operation -> cost, Configuration lists
# the knobs, Performance gives tuning advice, and Security covers atomicity
# and per-client buckets. Consolidating them would make each page worse, so
# they stay — but the *numbers* they share are pinned here instead, which is
# what actually drifted (the three tool-name-keyed exceptions were documented
# two different ways at once).

# Page -> the minimum number of operation-keyed rows the gate must still see.
# The floor is what stops a page from silently contributing nothing:
# configuration.mdx writes its keys as `"get_binary_entry"` (quotes inside the
# backticks), which the first version of this gate did not match, so 13 of its
# 14 rows went unverified while the test happily passed.
#
# performance-optimization.mdx keys its cost table by tool call, and
# security-best-practices.mdx states costs in prose — neither can be scanned by
# operation name, so neither is listed rather than being listed and silently
# contributing zero.
_RATE_LIMIT_PAGES = {
    "website/src/content/docs/api-reference.mdx": 10,
    "website/src/content/docs/configuration.mdx": 10,
}


def test_documented_rate_limit_costs_match_code() -> None:
    """Every `| <operation> | ... | <cost> |` row must match the real cost."""
    from openzim_mcp.defaults import RATE_LIMIT_COSTS

    wrong: list[str] = []
    checked: dict[str, int] = {}
    for rel in _RATE_LIMIT_PAGES:
        path = REPO / rel
        checked[rel] = 0
        if not path.is_file():
            wrong.append(f"{rel}: missing")
            continue
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            if not line.startswith("|"):
                continue
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if len(cells) < 2:
                continue
            tail = cells[-1]
            if not tail.isdigit():
                continue
            claimed = int(tail)
            for op, real in RATE_LIMIT_COSTS.items():
                # Both `get_entry` and `"get_entry"` appear in the corpus.
                if f"`{op}`" not in line and f'`"{op}"`' not in line:
                    continue
                checked[rel] += 1
                if claimed != real:
                    wrong.append(
                        f"{rel}:{lineno}: says {op} costs {claimed}, code says {real}"
                    )
    assert (
        not wrong
    ), "documented rate-limit costs disagree with code:\n  " + "\n  ".join(wrong)

    thin = [
        f"{rel}: only {n} rows checked, expected >= {_RATE_LIMIT_PAGES[rel]}"
        for rel, n in checked.items()
        if n < _RATE_LIMIT_PAGES[rel]
    ]
    assert not thin, (
        "the rate-limit gate stopped seeing rows it used to check — the table "
        "moved, was reformatted, or the key style changed, so the assertions "
        "above are now vacuous:\n  " + "\n  ".join(thin)
    )


def test_tools_without_their_own_cost_entry_are_described_as_default() -> None:
    """zim_query / zim_get_section / zim_health charge the ``default`` cost.

    They have no ``RATE_LIMIT_COSTS`` entry and are bucketed on their wire tool
    name. Performance guidance once said keys are "never the tool names",
    which is wrong for exactly these three.
    """
    from openzim_mcp.defaults import RATE_LIMIT_COSTS

    for tool in ("zim_query", "zim_get_section", "zim_health"):
        assert tool not in RATE_LIMIT_COSTS, (
            f"{tool} gained a RATE_LIMIT_COSTS entry — the docs describe it as "
            "charging the default cost under its own tool name. Update "
            "api-reference.mdx and performance-optimization.mdx together."
        )


# --------------------------------------------------------------------------
# 7. Every phrasing in the simple-mode phrasebook must actually dispatch.
# --------------------------------------------------------------------------

# In simple mode `zim_query` is the entire tool surface, so a documented
# phrasing that does not route is not a doc defect — it is a dead end with no
# workaround. This gate exists because the first version of the phrasebook
# shipped "get the image Logo.png", which falls through to full-text search:
# the binary pattern requires the verb adjacent to the noun, and the article
# breaks it.
#
# The check is that every example in a row agrees with the others in that row.
# That needs no label-to-intent mapping and catches the real failure shape —
# one row's examples splitting across two intents.

_PHRASEBOOK_ROW = re.compile(r"^\|\s*([^|]+?)\s*\|\s*((?:\"[^\"]+\"\s*,?\s*)+)\|", re.M)


def _phrasebook_rows() -> list[tuple[str, list[str]]]:
    text = _API_REFERENCE.read_text(encoding="utf-8")
    # Anchor on the section heading and stop at the next blank-line-separated
    # paragraph after the table, rather than on a prose sentence: the first
    # version of this gate keyed the end on "Three phrasings that trip people
    # up", so correcting that count word to "Phrasings" raised ValueError and
    # errored all three phrasebook tests at once.
    start = text.index("### Recognized phrasings")
    rest = text[start:]
    end = start + (rest.index("\n\n**") if "\n\n**" in rest else len(rest))
    return [
        (m.group(1), re.findall(r'"([^"]+)"', m.group(2)))
        for m in _PHRASEBOOK_ROW.finditer(text[start:end])
    ]


def test_phrasebook_has_rows() -> None:
    rows = _phrasebook_rows()
    assert len(rows) >= 15, f"only parsed {len(rows)} phrasebook rows — regex drifted?"


def test_every_documented_phrasing_dispatches_consistently() -> None:
    """All examples in one row must route to the same intent."""
    from openzim_mcp.intent_parser import IntentParser

    parser = IntentParser()
    broken: list[str] = []
    for label, examples in _phrasebook_rows():
        if len(examples) < 2:
            continue
        seen = {ex: parser.parse_intent(ex)[0] for ex in examples}
        if len(set(seen.values())) > 1:
            detail = ", ".join(f"{ex!r} -> {i}" for ex, i in seen.items())
            broken.append(f"{label}: {detail}")
    assert not broken, (
        "phrasebook rows whose examples do not all reach the same intent — a "
        "documented phrasing that misroutes is a dead end for simple-mode "
        "callers:\n  " + "\n  ".join(broken)
    )


def test_no_documented_phrasing_falls_through_to_bare_search() -> None:
    """A row that is not about search must not route to ``search``.

    ``search`` is the lowest-specificity pattern, so it is where a phrasing
    that matches nothing else lands. A non-search row reaching it means the
    example is wrong.
    """
    from openzim_mcp.intent_parser import IntentParser

    parser = IntentParser()
    fell_through: list[str] = []
    for label, examples in _phrasebook_rows():
        if "search" in label.lower():
            continue
        for ex in examples:
            if parser.parse_intent(ex)[0] == "search":
                fell_through.append(f"{label}: {ex!r} falls through to `search`")
    assert not fell_through, (
        "documented phrasings that silently become a full-text search:\n  "
        + "\n  ".join(fell_through)
    )


# --------------------------------------------------------------------------
# 4. The generated llms.txt must describe the surface that ships.
# --------------------------------------------------------------------------

_LLMS_TXT_SRC = REPO / "website" / "src" / "pages" / "llms.txt.ts"

# The first element of each `TOOLS` row: `['zim_get_section', '...']` on one
# line, or `[\n  'zim_query',\n ...` split across several.
_LLMS_TOOL_RE = re.compile(r"\[\s*\n?\s*'(zim_[a-z_]+)'")


def _llms_txt_tools() -> list[str]:
    """Tool names from the TOOLS table, ignoring commented-out rows.

    The comment strip is load-bearing: the first version of this helper
    matched raw text, so commenting a row out left it visible to the gate and
    a mutation that removed ``zim_health`` from the shipped file passed.
    """
    src = _LLMS_TXT_SRC.read_text(encoding="utf-8")
    block = src.split("const TOOLS", 1)[1].split("\n];", 1)[0]
    live = "\n".join(
        line for line in block.splitlines() if not line.lstrip().startswith("//")
    )
    return _LLMS_TOOL_RE.findall(live)


def _registered_tools() -> list[str]:
    allowed = tempfile.mkdtemp(prefix="openzim_mcp_llms_txt_")
    cfg = OpenZimMcpConfig(allowed_directories=[allowed], tool_mode="advanced")
    return list(OpenZimMcpServer(cfg).mcp._tool_manager._tools)


def test_llms_txt_lists_the_live_tool_surface() -> None:
    """The one half of llms.txt Astro cannot derive from the collection.

    The `## Documentation` index is generated from the content collection, so
    it cannot go stale. The tool list describes the Python server, which the
    build has no way to reach — which is exactly the shape of every other
    hand-copied fact in this repo. This is the gate that stands in for the
    derivation: names, count and order, against a live advanced-mode server.
    """
    assert _LLMS_TXT_SRC.is_file(), "llms.txt is generated by an endpoint; it moved"
    documented = _llms_txt_tools()
    live = _registered_tools()
    assert documented == live, (
        "website/src/pages/llms.txt.ts's TOOLS table no longer matches the "
        f"registered advanced surface.\n  llms.txt: {documented}\n  server:   {live}"
    )


def test_llms_txt_is_generated_not_a_static_file() -> None:
    """A static copy left in `public/` would win and silently shadow the route.

    Astro copies `public/` verbatim into `dist/`, so a re-created
    `public/llms.txt` would overwrite the generated one with no warning at
    build time and no error anywhere — the exact stale file this route
    replaced.
    """
    static = REPO / "website" / "public" / "llms.txt"
    assert not static.exists(), (
        f"{static.relative_to(REPO)} exists again and shadows the generated "
        "route at website/src/pages/llms.txt.ts. Delete it and put the content "
        "in the route."
    )


# --------------------------------------------------------------------------
# 5. Documentation that would mislead a reader on a DEFAULT install.
# --------------------------------------------------------------------------

_DOC_PAGES = sorted((REPO / "website" / "src" / "content" / "docs").glob("*.mdx"))

# The body of a fenced block, with its info string. Only fenced blocks are
# scanned: prose *about* a bad phrasing (troubleshooting says "do not ask
# ...") must stay legal, while the same words offered as something to run
# must not.
_FENCE_RE = re.compile(r"^```([a-z]*)\n(.*?)^```", re.MULTILINE | re.DOTALL)
_HEALTH_ASK_RE = re.compile(r"server (?:health|configuration)", re.IGNORECASE)


def test_no_page_offers_a_natural_language_server_health_ask() -> None:
    """Simple mode is the default and has no health intent.

    ``zim_health`` is registered in advanced mode only, and the intent parser
    has nothing that routes a health or configuration request — so a phrase
    like "check the server health and configuration", offered in a fenced
    block as something to ask, is parsed as a *topic* and searched inside the
    archive. The reader gets ``No search results found`` and reads it as a
    broken server. Both the troubleshooting page's first diagnostic and the
    configuration page's validation step shipped exactly that.

    The premise is asserted first, so this test fails loudly rather than
    silently going vacuous if a health intent is ever added.
    """
    from openzim_mcp.intent_parser import IntentParser

    parser = IntentParser()
    probe = "check the server health and configuration"
    intent, _params, _confidence = parser.parse_intent(probe)
    assert intent not in {"health", "server_health", "configuration", "config"}, (
        f"the intent parser now routes {probe!r} to {intent!r}. Simple mode can "
        "answer a health ask after all — delete this test and restore the "
        "natural-language examples it forbids."
    )

    offenders: list[str] = []
    for path in _DOC_PAGES:
        text = path.read_text(encoding="utf-8")
        for match in _FENCE_RE.finditer(text):
            body = match.group(2)
            if not _HEALTH_ASK_RE.search(body):
                continue
            # `zim_health()` and the HTTP probes are the correct advanced-mode
            # and transport-level answers; only a quoted natural-language ask
            # is the defect.
            for line in body.splitlines():
                stripped = line.strip()
                if not _HEALTH_ASK_RE.search(stripped):
                    continue
                if stripped.startswith('"') or stripped.startswith("'"):
                    lineno = text[: match.start()].count("\n") + 1
                    rel = path.relative_to(REPO)
                    offenders.append(f"{rel}:~{lineno}: {stripped}")

    assert not offenders, (
        "a fenced block offers a natural-language server-health ask, which "
        "reaches nothing on a default (simple-mode) install and searches the "
        "archive for those words instead. Use `zim_health()` and say it needs "
        "advanced mode, or use the `/healthz` and `/readyz` probes:\n  "
        + "\n  ".join(offenders)
    )


# --------------------------------------------------------------------------
# 6. One home per deployment profile.
# --------------------------------------------------------------------------


def test_deployment_profiles_have_exactly_one_home() -> None:
    """The same profile written on two pages drifts on the first correction.

    Configuration and Performance both carried a "Production HTTP service"
    block, with different cache sizes and different rate limits. The
    persistence-path and tool-mode corrections landed on one copy only, so the
    two recipes disagreed about what a production deployment should set.
    Configuration owns them now; Performance links there and keeps the
    symptom-to-knob table instead.
    """
    heading = "### Production HTTP service"
    homes = [
        str(p.relative_to(REPO))
        for p in _DOC_PAGES
        if heading in p.read_text(encoding="utf-8")
    ]
    assert homes == ["website/src/content/docs/configuration.mdx"], (
        f"{heading!r} must appear on exactly one page (Configuration). Found: "
        f"{homes}. Link to /openzim-mcp/docs/configuration/#profiles instead of "
        "copying the block."
    )


# --------------------------------------------------------------------------
# 7. Dependency bots must not cut releases.
# --------------------------------------------------------------------------


def test_dependabot_prefixes_do_not_cut_releases_for_non_shipped_deps() -> None:
    """Only the pip ecosystem may use a changelog-visible commit prefix.

    ``deps`` is ``"hidden": false`` in release-please-config.json, so a commit
    carrying it cuts a patch release — v3.1.2 came from a lone ``deps:``
    commit. That is correct for Python dependencies, which ship inside the
    wheel. It is wrong for the actions, the base image and the website's npm
    tree: a devDependency bump to a static site would publish a wheel to PyPI
    whose only change is not in it.
    """
    import yaml

    config = yaml.safe_load(
        (REPO / ".github" / "dependabot.yml").read_text(encoding="utf-8")
    )
    rp = json.loads((REPO / "release-please-config.json").read_text(encoding="utf-8"))
    visible = {
        section["type"]
        for section in rp["packages"]["."]["changelog-sections"]
        if not section.get("hidden", False)
    }
    assert "deps" in visible, (
        "release-please no longer treats `deps` as release-cutting; this test's "
        "premise is gone and its exemption for the pip ecosystem is stale."
    )

    offenders = []
    for update in config["updates"]:
        ecosystem = update["package-ecosystem"]
        prefix = update.get("commit-message", {}).get("prefix")
        assert prefix, f"{ecosystem}: no commit-message prefix configured"
        if ecosystem == "pip":
            continue  # ships in the wheel; a release is the right outcome
        if prefix in visible:
            offenders.append(
                f"{ecosystem} (directory {update['directory']}): {prefix!r}"
            )

    assert not offenders, (
        "these Dependabot ecosystems use a commit prefix release-please "
        f"publishes a release for ({sorted(visible)}), but their updates do not "
        "ship in the wheel. Use `ci`:\n  " + "\n  ".join(offenders)
    )


def test_dependabot_watches_the_website_dependency_tree() -> None:
    """The site's build toolchain is a dependency surface like any other.

    Astro, Vite and Pagefind plus a hand-written security ``overrides`` block
    live in website/package-lock.json. Every other tree here has an ecosystem;
    this one had none, so nothing would have told anyone about an advisory in
    the toolchain that builds the published documentation.
    """
    import yaml

    config = yaml.safe_load(
        (REPO / ".github" / "dependabot.yml").read_text(encoding="utf-8")
    )
    npm = [u for u in config["updates"] if u["package-ecosystem"] == "npm"]
    assert len(npm) == 1, f"expected exactly one npm ecosystem, found {len(npm)}"
    assert npm[0]["directory"] == "/website", (
        f"npm ecosystem points at {npm[0]['directory']!r}; package.json and "
        "package-lock.json are in /website"
    )
    assert (REPO / "website" / "package-lock.json").is_file()


# --------------------------------------------------------------------------
# 8. The reveal animation must not be the only thing rendering the page.
# --------------------------------------------------------------------------

_STYLES_CSS = REPO / "website" / "public" / "assets" / "styles.css"
_SCRIPT_JS = REPO / "website" / "public" / "assets" / "script.js"
_LAYOUTS = sorted((REPO / "website" / "src" / "layouts").glob("*.astro"))

_CSS_COMMENT_RE = re.compile(r"/\*.*?\*/", re.DOTALL)
_CSS_RULE_RE = re.compile(r"([^{}]*)\{([^{}]*)\}")
_OPACITY_ZERO_RE = re.compile(r"opacity:\s*0\s*[;}]")


def test_reveal_animation_does_not_hide_content_without_js() -> None:
    """`[data-reveal] { opacity: 0 }` unscoped is a blank page with JS off.

    Four of the landing page's five sections were invisible to anyone without
    scripting, and invisible again any time the deferred bundle failed to
    load: the CSS hid them unconditionally and only `script.js` ever added the
    `.revealed` class that brought them back. The hiding half is now scoped to
    `.js`, which a head script adds and — crucially — removes again on `load`
    if `script.js` never announced itself.

    Comments are stripped before matching, or a comment mentioning `.js` next
    to the rule would satisfy this test without the rule being scoped at all.
    """
    css = _CSS_COMMENT_RE.sub("", _STYLES_CSS.read_text(encoding="utf-8"))

    checked = 0
    unscoped: list[str] = []
    for selector, body in _CSS_RULE_RE.findall(css):
        if "[data-reveal]" not in selector or not _OPACITY_ZERO_RE.search(body):
            continue
        checked += 1
        if ".js" not in selector:
            unscoped.append(" ".join(selector.split()))
    assert checked, (
        "no `[data-reveal]` rule setting `opacity: 0` was found in styles.css — "
        "this test has gone vacuous; the reveal mechanism was renamed or removed"
    )
    assert not unscoped, (
        "these rules hide `[data-reveal]` content for every visitor, including "
        f"those `script.js` never reaches: {unscoped}. Scope them under `.js`."
    )

    script = _SCRIPT_JS.read_text(encoding="utf-8")
    assert "classList.add('js-ready')" in script, (
        "script.js must announce itself with `js-ready`; the layouts' head "
        "script strips `.js` on `load` without it, so the reveal would never "
        "arm and the animation would be dead"
    )

    # Every layout, unconditionally. styles.css is a single site-wide sheet,
    # so the `.js` contract is site-wide too: a layout without the flag renders
    # any `[data-reveal]` markup beneath it permanently hidden. Scoping this
    # check to layouts that mention script.js let a mutation through — neither
    # layout links the bundle directly (index.astro and DocsLayout's body do),
    # so the check covered nothing that mattered.
    assert _LAYOUTS, "no layouts found — this test has gone vacuous"
    missing_flag = [
        str(path.relative_to(REPO))
        for path in _LAYOUTS
        if "classList.add('js')" not in path.read_text(encoding="utf-8")
    ]
    assert not missing_flag, (
        f"these layouts never set the `.js` flag: {missing_flag}. Any "
        "`[data-reveal]` section rendered beneath one stays at `opacity: 0` "
        "forever, because only `.js [data-reveal].revealed` brings it back."
    )
    missing_fallback = [
        str(path.relative_to(REPO))
        for path in _LAYOUTS
        if "classList.remove('js')" not in path.read_text(encoding="utf-8")
    ]
    assert not missing_fallback, (
        f"these layouts add `.js` but never remove it: {missing_fallback}. The "
        "`load` fallback is what keeps a failed script.js from leaving the page "
        "permanently at `opacity: 0`."
    )


def test_no_unstamped_doc_names_the_current_version() -> None:
    """A current-version literal on a line nobody stamps is rot with a fuse.

    ``test_version_declarations_are_stamped_or_current`` only sees the
    ``Version: X.Y.Z`` *declaration* shape. It does not see a version sitting
    anywhere else — sample command output, a pinned ``uvx pkg@X.Y.Z``, a code
    comment — and every one of those is wrong the moment the next release
    ships. This sweep introduced one itself (``# openzim-mcp 3.2.3`` under a
    ``--version`` example on the troubleshooting page) and the declaration
    gate did not notice.

    So: the current version may appear only on a line release-please stamps.
    Anywhere else, derive it, or write the sentence without it. Past versions
    are untouched — a claim about what v2.3.0 did stays true.
    """
    pattern = re.compile(r"(?<![\w.])v?" + re.escape(__version__) + r"(?![\w.])")
    offenders: list[str] = []
    for path in _doc_files():
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            if "x-release-please" in line:
                continue  # release-please rewrites this line every release
            if pattern.search(line):
                rel = path.relative_to(REPO)
                offenders.append(f"{rel}:{lineno}: {line.strip()[:100]}")

    assert not offenders, (
        f"the current version ({__version__}) appears on lines nothing stamps, "
        "so each becomes wrong at the next release:\n  "
        + "\n  ".join(offenders)
        + "\nAdd an `x-release-please-version` annotation AND register the file "
        "in release-please-config.json's extra-files, derive the value, or "
        "reword so the version is not named."
    )


def test_llms_index_advertises_the_routes_that_exist() -> None:
    """The index, the full corpus and the per-page Markdown must agree.

    `llms.txt` is only useful to an agent if the cheap paths it names are real.
    Both are generated from the same content collection as the index, so they
    cannot fall behind a new page — but a renamed route file would leave the
    index pointing at a 404, and nothing else would notice, because the link
    checker only reads `href`s out of built HTML.
    """
    index = _LLMS_TXT_SRC.read_text(encoding="utf-8")
    pages = REPO / "website" / "src" / "pages"

    full = pages / "llms-full.txt.ts"
    per_page = pages / "docs" / "[...slug].md.ts"
    assert (
        full.is_file()
    ), f"{full.relative_to(REPO)} is gone but llms.txt still links it"
    assert per_page.is_file(), (
        f"{per_page.relative_to(REPO)} is gone but llms.txt still advertises "
        "per-page Markdown"
    )

    assert "/llms-full.txt" in index, (
        "llms.txt no longer points at llms-full.txt — an agent has no way to "
        "discover the whole-corpus fetch"
    )
    assert "/docs/<slug>.md" in index, (
        "llms.txt no longer documents the per-page `.md` convention, so the "
        "shell-free route is undiscoverable"
    )

    # Both generated routes must derive their page list from the collection.
    # A hardcoded list is how the static llms.txt went stale in the first place.
    for path in (full, per_page):
        text = path.read_text(encoding="utf-8")
        assert "getCollection" in text, (
            f"{path.relative_to(REPO)} no longer reads the content collection; "
            "a hand-maintained page list is exactly the drift these routes replaced"
        )


def test_documented_preset_fields_match_the_models() -> None:
    """The preset override format is operator-authored TOML with `extra=forbid`.

    A field named in the docs that the model does not accept produces a file
    the server drops with a warning and no other signal — the operator sees
    generic behaviour and no error. So the documented field list has to be the
    model's field list, and the documented `summary_style` values have to be
    the literal's values.
    """
    import typing

    from openzim_mcp import preset_data

    page = (REPO / "website/src/content/docs/configuration.mdx").read_text(
        encoding="utf-8"
    )
    section = page.split("## Archive-type presets", 1)[1].split("\n## ", 1)[0]

    preset_fields = set(preset_data.ArchivePreset.model_fields)
    pin_only = set(preset_data.ArchivePin.model_fields) - preset_fields
    assert pin_only == {"type"}, f"ArchivePin gained/lost a field: {pin_only}"

    for field in preset_fields | pin_only:
        assert f"`{field}`" in section, (
            f"`{field}` is accepted in a preset override but the Configuration "
            "page's Archive-type presets section does not document it"
        )

    styles = set(typing.get_args(preset_data.SummaryStyle))
    for style in styles:
        assert (
            f'"{style}"' in section
        ), f'summary_style accepts "{style}" but the section does not list it'
    # And nothing invented: every quoted style in the section must be real.
    quoted = set(re.findall(r'`"([a-z_]+)"`', section))
    invented = quoted - styles
    assert (
        not invented
    ), f"the section offers summary_style values the model rejects: {invented}"

    # The confidence gate is the rule an operator gets wrong; keep it named.
    assert "high" in section and "medium" in section, (
        "the confidence gate is what decides whether a type preset applies at "
        "all — the section must still explain it"
    )


def test_no_contributor_surface_sends_people_to_discussions() -> None:
    """GitHub Discussions is disabled on this repository.

    `has_discussions` is false and `/discussions` returns 404, so every
    instruction to "search discussions" or "ask in Discussions" sends a
    contributor to a 404 before they have written a word. An earlier pass
    cleared this out of the FAQ and the Code of Conduct and missed the issue
    templates, which is the surface a contributor actually hits first.

    The check is deliberately narrow — the security template legitimately uses
    "general security discussion" to name a *kind of issue*, which is not a
    pointer at the disabled feature.
    """
    surfaces = [
        *sorted((REPO / ".github" / "ISSUE_TEMPLATE").glob("*.yml")),
        *(p for p in (REPO / ".github" / "PULL_REQUEST_TEMPLATE.md",) if p.is_file()),
        REPO / "CONTRIBUTING.md",
        REPO / "CODE_OF_CONDUCT.md",
        REPO / "README.md",
        REPO / "SECURITY.md",
        *sorted((REPO / "website" / "src" / "content" / "docs").glob("*.mdx")),
    ]
    # "search ... discussions", "in Discussions", "/discussions", "GitHub Discussions"
    pointer = re.compile(
        r"github\.com/[\w-]+/[\w-]+/discussions"
        r"|GitHub Discussions"
        r"|issues and discussions"
        r"|(?:search|ask|post|check)[^.\n]{0,40}\bdiscussions\b",
        re.IGNORECASE,
    )
    offenders = []
    for path in surfaces:
        if not path.is_file():
            continue
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            if pointer.search(line):
                offenders.append(
                    f"{path.relative_to(REPO)}:{lineno}: {line.strip()[:90]}"
                )

    assert not offenders, (
        "these lines point a contributor at GitHub Discussions, which is "
        "disabled on this repository (has_discussions=false, /discussions 404s):"
        "\n  " + "\n  ".join(offenders)
    )


# Row label -> the intent `IntentParser` must emit for that row's examples.
#
# The three gates above check the phrasebook against *itself* — rows are
# internally consistent, and no non-search row falls through to search. Neither
# notices a row whose examples agree with each other and reach the wrong
# handler: "show article X" and "list article X" both dispatch to `browse`
# consistently, and both are wrong. This map is what turns a consistency check
# into a correctness one.
_PHRASEBOOK_LABEL_TO_INTENT = {
    "List archives": "list_files",
    "Main page": "main_page",
    "List namespaces": "list_namespaces",
    "Archive metadata": "metadata",
    "Fetch an article": "get_article",
    "Topic lookup": "tell_me_about",
    "Full-text search": "search",
    "Cross-archive search": "search_all",
    "Filtered search": "filtered_search",
    "Title lookup": "find_by_title",
    "Autocomplete": "suggestions",
    "Section outline": "structure",
    "Table of contents": "toc",
    "Summary": "summary",
    "One section": "get_section",
    "Outbound links": "links",
    "Related articles": "related",
    "Browse a namespace": "browse",
    "Walk a namespace": "walk_namespace",
    "Batch fetch": "get_zim_entries",
    "Binary content": "binary",
}


def test_phrasebook_covers_every_dispatched_intent() -> None:
    """The table must be the whole surface, not a sample.

    Simple mode is the default and registers one tool, so an intent missing
    from this table is a capability with no discoverable phrasing. The mapping
    below is also asserted against the live handler map, so a new intent fails
    here rather than shipping undocumented.
    """
    from openzim_mcp.simple_tools import SimpleToolsHandler

    # `list_files` and `search_all` dispatch from bypasses ahead of the map.
    dispatched = set(SimpleToolsHandler._INTENT_HANDLERS) | {"list_files"}
    mapped = set(_PHRASEBOOK_LABEL_TO_INTENT.values())

    assert mapped == dispatched, (
        "the phrasebook's intent coverage no longer matches the dispatch "
        f"surface.\n  missing from the page: {sorted(dispatched - mapped)}"
        f"\n  documented but not dispatched: {sorted(mapped - dispatched)}"
    )

    labels = {label for label, _ in _phrasebook_rows()}
    unmapped = labels - set(_PHRASEBOOK_LABEL_TO_INTENT)
    assert not unmapped, (
        f"phrasebook rows with no intent mapping: {sorted(unmapped)} — add "
        "them to _PHRASEBOOK_LABEL_TO_INTENT so their examples get checked"
    )
    missing_rows = set(_PHRASEBOOK_LABEL_TO_INTENT) - labels
    assert (
        not missing_rows
    ), f"these rows were removed from the published table: {sorted(missing_rows)}"


def test_every_documented_phrasing_reaches_its_own_intent() -> None:
    """Each example must reach the intent its row is about.

    Consistency is not correctness. "show article Evolution" and "list article
    Evolution" both dispatch to `browse` — agreeing with each other, agreeing
    with nothing the reader wanted, and answering **Missing or Invalid
    Namespace**. Running each example against the parser is the only check that
    catches that.
    """
    from openzim_mcp.intent_parser import IntentParser

    parser = IntentParser()
    rows = _phrasebook_rows()
    assert len(rows) >= 20, f"only {len(rows)} rows parsed — the regex drifted"

    wrong: list[str] = []
    for label, examples in rows:
        expected = _PHRASEBOOK_LABEL_TO_INTENT.get(label)
        if expected is None:
            continue  # the coverage test above owns this failure
        for example in examples:
            got, _params, confidence = parser.parse_intent(example)
            if got != expected:
                wrong.append(
                    f"{label}: {example!r} should reach {expected!r} but "
                    f"dispatches to {got!r} (confidence {confidence})"
                )

    assert not wrong, (
        "documented phrasings that reach the wrong handler — a reader copying "
        "one gets a plausible-looking wrong answer:\n  " + "\n  ".join(wrong)
    )


# --------------------------------------------------------------------------
# 9. The documented cursor failures must be the ones the code produces.
# --------------------------------------------------------------------------

_TEST_ARCHIVE = (
    REPO
    / "test_data/zim-testing-suite/withns/wikipedia_en_climate_change_mini_2024-06.zim"
)


def _cursor_table_operations() -> set[str]:
    """The `operation` values the API reference's cursor table promises.

    Body rows only. The header cell is itself ``\u0060operation\u0060``, so a
    naive row regex captures it and the set never matches what the code emits.
    """
    page = _API_REFERENCE.read_text(encoding="utf-8")
    table = page.split("### When a cursor is refused", 1)[1].split("\n**", 1)[0]
    body = table.split("|---", 1)[1]
    return set(re.findall(r"^\|\s*`([a-z_]+)`\s*\|", body, re.MULTILINE))


@pytest.mark.skipif(
    not _TEST_ARCHIVE.is_file(),
    reason="needs the zim-testing-suite fixture (make download-test-data-all)",
)
def test_documented_cursor_failures_are_the_ones_produced() -> None:
    """Each refusal in the table is produced for real and compared.

    Cursor errors are the one place a client cannot recover by guessing: the
    envelope names what to do, and every one of these codes carries different
    advice. Two of the four rules this section was written from turned out to
    be backwards when run — an explicit `limit` beats the cursor's encoded page
    size, not the other way round — so the table is checked by producing the
    failures rather than by reading the raising code.
    """
    import asyncio

    cfg = OpenZimMcpConfig(
        allowed_directories=[str(_TEST_ARCHIVE.parent)], tool_mode="advanced"
    )
    cfg.rate_limit.enabled = False
    tools = OpenZimMcpServer(cfg).mcp._tool_manager._tools

    def call(name: str, **kwargs: object) -> dict:
        fn = tools[name].fn
        out = (
            asyncio.run(fn(**kwargs))
            if asyncio.iscoroutinefunction(fn)
            else fn(**kwargs)
        )
        return out if isinstance(out, dict) else {}

    archive = str(_TEST_ARCHIVE)
    first = call(
        "zim_browse", zim_file_path=archive, namespace="A", mode="page", limit=5
    )
    cursor = first.get("next_cursor")
    assert (
        cursor
    ), "browse page mode stopped issuing a cursor; the table's premise is gone"

    produced = {
        # a cursor from another tool
        call(
            "zim_links",
            zim_file_path=archive,
            entry_path="A/Climate_change",
            direction="outbound",
            cursor=cursor,
        ).get("operation"),
        # a direction that does not paginate
        call(
            "zim_links",
            zim_file_path=archive,
            entry_path="A/Climate_change",
            direction="related",
            cursor=cursor,
        ).get("operation"),
        # the tool that refuses every cursor
        call("zim_search", zim_file_path=archive, query="climate", cursor=cursor).get(
            "operation"
        ),
        # garbage
        call(
            "zim_browse",
            zim_file_path=archive,
            namespace="A",
            mode="page",
            cursor="not-a-cursor",
        ).get("operation"),
        # right tool, different namespace
        call(
            "zim_browse",
            zim_file_path=archive,
            namespace="M",
            mode="page",
            cursor=cursor,
        ).get("operation"),
    }
    produced.discard(None)

    documented = _cursor_table_operations()
    undocumented = produced - documented
    assert not undocumented, (
        f"these cursor refusals are produced but the table does not list them: "
        f"{sorted(undocumented)}"
    )
    # Every documented code must still be reachable; a stale row is advice for
    # an envelope no client will ever see.
    assert produced == documented, (
        f"the cursor table lists codes nothing produced here: "
        f"{sorted(documented - produced)} (produced: {sorted(produced)})"
    )


@pytest.mark.skipif(
    not _TEST_ARCHIVE.is_file(),
    reason="needs the zim-testing-suite fixture (make download-test-data-all)",
)
def test_cursor_precedence_is_documented_the_way_it_behaves() -> None:
    """`limit` beats the cursor's page size; the cursor's offset beats `offset`.

    This is the asymmetry the section exists to state, and the one both the
    original research and my own first assumption got backwards.
    """
    import asyncio

    cfg = OpenZimMcpConfig(
        allowed_directories=[str(_TEST_ARCHIVE.parent)], tool_mode="advanced"
    )
    cfg.rate_limit.enabled = False
    tools = OpenZimMcpServer(cfg).mcp._tool_manager._tools

    def call(name: str, **kwargs: object) -> dict:
        fn = tools[name].fn
        out = (
            asyncio.run(fn(**kwargs))
            if asyncio.iscoroutinefunction(fn)
            else fn(**kwargs)
        )
        return out if isinstance(out, dict) else {}

    archive = str(_TEST_ARCHIVE)
    first = call(
        "zim_browse", zim_file_path=archive, namespace="A", mode="page", limit=5
    )
    cursor = first["next_cursor"]
    resumed = call(
        "zim_browse",
        zim_file_path=archive,
        namespace="A",
        mode="page",
        cursor=cursor,
        limit=2,
    )
    assert len(resumed["results"]) == 2, (
        "an explicit `limit` no longer overrides the cursor's encoded page size "
        f"(got {len(resumed['results'])} rows for limit=2) — the API reference's "
        "Cursors section states that it does"
    )

    walk = call(
        "zim_browse", zim_file_path=archive, namespace="A", mode="walk", limit=3
    )
    walked = call(
        "zim_browse",
        zim_file_path=archive,
        namespace="A",
        mode="walk",
        limit=3,
        offset=3,
    )
    assert [r["path"] for r in walk["results"]] == [
        r["path"] for r in walked["results"]
    ], (
        "`zim_browse(mode='walk')` now honours `offset` — the Cursors section "
        "warns that it does not and that walk must be driven by its cursor"
    )


# --------------------------------------------------------------------------
# 10. The published rate-limit costs must be the costs that are charged.
# --------------------------------------------------------------------------

# | `zim_get(binary=True)` | `"get_binary_entry"` | 3 |
_COST_ROW_RE = re.compile(
    r'^\|[^|]*\|\s*`"([a-z_]+)"`[^|]*\|\s*(\d+)\s*\|', re.MULTILINE
)


def test_published_rate_limit_costs_match_the_table_in_code() -> None:
    """Every documented cost must equal `RATE_LIMIT_COSTS`.

    The cost model is written out on five pages and has contradicted itself
    before. Rather than delete the copies — a reference page has a fair claim
    to carrying it — every copy is checked against `defaults.py`, so a stale
    one fails instead of quietly disagreeing with its neighbours.
    """
    from openzim_mcp.defaults import RATE_LIMIT_COSTS

    pages = [
        REPO / "website/src/content/docs/configuration.mdx",
        REPO / "website/src/content/docs/api-reference.mdx",
        REPO / "website/src/content/docs/performance-optimization.mdx",
    ]
    wrong: list[str] = []
    checked = 0
    for path in pages:
        if not path.is_file():
            continue
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            for op, cost in _COST_ROW_RE.findall(line):
                if op not in RATE_LIMIT_COSTS:
                    # The three wire-keyed tools have no entry on purpose and
                    # charge the `default` cost.
                    expected = RATE_LIMIT_COSTS["default"]
                else:
                    expected = RATE_LIMIT_COSTS[op]
                checked += 1
                if int(cost) != expected:
                    wrong.append(
                        f"{path.relative_to(REPO)}:{lineno}: {op!r} documented "
                        f"as {cost}, charged {expected}"
                    )
    assert checked >= 12, (
        f"only {checked} cost rows parsed across the doc pages — the table "
        "shape changed and this gate has gone nearly vacuous"
    )
    assert (
        not wrong
    ), "documented rate-limit costs that are not charged:\n  " + "\n  ".join(wrong)


def test_every_charged_operation_is_documented_somewhere() -> None:
    """A cost in the code with no row is a limit an operator cannot tune."""
    from openzim_mcp.defaults import RATE_LIMIT_COSTS

    text = (REPO / "website/src/content/docs/configuration.mdx").read_text(
        encoding="utf-8"
    )
    missing = [
        op for op in RATE_LIMIT_COSTS if op != "default" and f'`"{op}"`' not in text
    ]
    assert not missing, (
        f"these operations are charged but the Configuration cost table does "
        f"not list them: {sorted(missing)} — a `per_operation_limits` override "
        "cannot be written without the literal key"
    )


# --------------------------------------------------------------------------
# 11. The documented trust boundary must be the one the code applies.
# --------------------------------------------------------------------------

_SECURITY_PAGE = REPO / "website/src/content/docs/security-best-practices.mdx"


def test_documented_fence_scope_matches_the_code() -> None:
    """The fenced-intent list is a security claim, so it is checked.

    The fence is provenance labelling for third-party archive text. A reader
    deciding whether to trust it needs the list of paths it covers to be exact
    — an intent silently added to or dropped from the code turns the published
    list into a false statement about a security control.
    """
    from openzim_mcp.compact_format import _CompactFormatMixin
    from openzim_mcp.simple_tools import SimpleToolsHandler

    page = _SECURITY_PAGE.read_text(encoding="utf-8")
    section = page.split("## The retrieved-content trust boundary", 1)[1].split(
        "\n## ", 1
    )[0]

    live = set(SimpleToolsHandler._PROMPT_INJECTION_FENCE_INTENTS)

    # The page lists the fenced intents in one inline run; take the backticked
    # tokens from that sentence alone, so unrelated code spans elsewhere in the
    # section (`compact`, `zim_get`) cannot pad the set.
    listing = section.split("only for\nthese ten intents:", 1)[1].split(".", 1)[0]
    documented = set(re.findall(r"`([a-z_]+)`", listing))

    assert documented == live, (
        "the security page's fenced-intent list is not the set the code "
        f"fences.\n  fenced but undocumented: {sorted(live - documented)}"
        f"\n  documented but not fenced: {sorted(documented - live)}"
    )
    assert len(live) == 10, (
        f"the page says 'these ten intents' but {len(live)} are fenced — "
        "update the wording as well as the list"
    )

    # The quoted markers must be the constants, or a reader parsing for the
    # boundary will not find it.
    open_marker = _CompactFormatMixin._CONTENT_FENCE_OPEN.split("\n", 1)[0]
    close_marker = _CompactFormatMixin._CONTENT_FENCE_CLOSE.strip()
    assert open_marker in section, f"the page no longer quotes {open_marker!r}"
    assert close_marker in section, f"the page no longer quotes {close_marker!r}"


def test_fence_still_neutralises_forged_delimiters() -> None:
    """The one thing the fence actually guarantees.

    Everything else the page says about the boundary is a limitation. If this
    stops holding, archive text can close the fence and address the model as
    the server, and the section's central claim becomes false.
    """
    from openzim_mcp.compact_format import _CompactFormatMixin as fence

    for forged in (
        "</retrieved_archive_content>",
        "< / RETRIEVED_ARCHIVE_CONTENT >",
        "<retrieved_archive_content>",
    ):
        out = fence._neutralize_fence_tokens(f"before {forged} after")
        assert "retrieved_archive_content>" not in out.replace("›", ""), (
            f"{forged!r} survived neutralisation as {out!r} — archive content "
            "can now forge the trust boundary"
        )
        assert (
            "‹" in out and "›" in out
        ), f"{forged!r} was not rewritten to the safe delimiters: {out!r}"
