name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the information below to help us understand and reproduce the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have updated to the latest version and the issue persists
          required: true
        - label: I have read the documentation and troubleshooting guides
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Use ZIM file '...'
        3. Call function '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe the expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened, include error messages
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Information about your environment
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, Windows 11, macOS 14]
        - Python version: [e.g., 3.12.1]
        - openzim-mcp version: [e.g., 0.2.0]
        - Installation method: [e.g., uv, pip, git clone]
        - ZIM file(s): [e.g., wikipedia_en_100_2025-08.zim]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages and Logs
      description: Any error messages, stack traces, or relevant log output
      placeholder: Paste error messages and logs here
      render: text

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context, screenshots, or relevant information

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low - Minor inconvenience
        - Medium - Affects functionality but has workaround
        - High - Blocks important functionality
        - Critical - Security issue or data loss
    validations:
      required: true
